"""
main.py — FastAPI application entry point for the Personal Finance Tracker backend.

Run locally:
    uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc

All routes except GET /health require a valid Supabase JWT in the
Authorization header:
    Authorization: Bearer <your-supabase-jwt>
"""

import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

from routers import plaid, transactions, budgets, goals, liabilities

load_dotenv()

app = FastAPI(
    title="Personal Finance Tracker API",
    description="Backend API for the Finance Tracker app. Handles Plaid bank sync and all CRUD operations.",
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------
# Read allowed origins from the environment so this works for both local dev
# (http://localhost:3000) and production (your Vercel URL).
_raw_origins = os.getenv("ALLOWED_ORIGINS", "http://localhost:3000")
allowed_origins = [o.strip() for o in _raw_origins.split(",") if o.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Authorization", "Content-Type"],
    allow_credentials=True,
)

# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

app.include_router(plaid.router)
app.include_router(transactions.router)
app.include_router(budgets.router)
app.include_router(goals.router)
app.include_router(liabilities.router)

# ---------------------------------------------------------------------------
# Health check (unauthenticated — used by load balancers/monitoring to confirm the app is up)
# ---------------------------------------------------------------------------

@app.get("/health", tags=["meta"])
def health():
    return {"status": "ok"}
